"""Add CandidateRelationship

Revision ID: 21aef34fcbaa
Revises: 9988bf5a33cc
Create Date: 2026-09-09 19:14:35.985809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '21aef34fcbaa'
down_revision: Union[str, Sequence[str], None] = '9988bf5a33cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source_candidate_id', sa.UUID(), nullable=False),
    sa.Column('target_candidate_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_RESOLUTION', 'REJECTED', name='candidatestatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['extraction_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['candidate_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_candidate_id'], ['candidate_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_relationships')
    # ### end Alembic commands ###
