"""Add source_record_reference to ResolvedEntity

Revision ID: 2e85e6765cff
Revises: 50d38fa87faf
Create Date: 2026-09-10 23:11:25.868863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e85e6765cff'
down_revision: Union[str, Sequence[str], None] = '50d38fa87faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolved_entities', sa.Column('source_record_reference', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resolved_entities', 'source_record_reference')
    # ### end Alembic commands ###
