"""add canonical models

Revision ID: 50d38fa87faf
Revises: 2c9e800a61d3
Create Date: 2026-09-10 13:49:09.505455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50d38fa87faf'
down_revision: Union[str, Sequence[str], None] = '2c9e800a61d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_node_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_label', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_node_records_canonical_id'), 'canonical_node_records', ['canonical_id'], unique=False)
    op.create_table('canonical_relationship_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_relationship_records_relationship_type'), 'canonical_relationship_records', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_canonical_relationship_records_source_id'), 'canonical_relationship_records', ['source_id'], unique=False)
    op.create_index(op.f('ix_canonical_relationship_records_target_id'), 'canonical_relationship_records', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_relationship_records_target_id'), table_name='canonical_relationship_records')
    op.drop_index(op.f('ix_canonical_relationship_records_source_id'), table_name='canonical_relationship_records')
    op.drop_index(op.f('ix_canonical_relationship_records_relationship_type'), table_name='canonical_relationship_records')
    op.drop_table('canonical_relationship_records')
    op.drop_index(op.f('ix_canonical_node_records_canonical_id'), table_name='canonical_node_records')
    op.drop_table('canonical_node_records')
    # ### end Alembic commands ###
