"""Add extraction models

Revision ID: 7f422f8d4e16
Revises: 176bc074fcf9
Create Date: 2026-09-09 17:06:08.423315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f422f8d4e16'
down_revision: Union[str, Sequence[str], None] = '176bc074fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='extractionstatus'), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('candidates_extracted', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('canonical_label', sa.String(length=255), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_method', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_RESOLUTION', 'REJECTED', name='candidatestatus'), nullable=False),
    sa.Column('source_document_id', sa.String(length=255), nullable=False),
    sa.Column('generation_batch_id', sa.String(length=255), nullable=True),
    sa.Column('audit_reference', sa.String(length=255), nullable=True),
    sa.Column('synthetic_flag', sa.Boolean(), nullable=True),
    sa.Column('source_dataset', sa.String(length=255), nullable=True),
    sa.Column('provenance_mode', sa.String(length=255), nullable=True),
    sa.Column('source_record_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['extraction_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_entities')
    op.drop_table('extraction_batches')
    # ### end Alembic commands ###
