"""Add resolution models

Revision ID: 932f3c331851
Revises: 21aef34fcbaa
Create Date: 2026-09-09 22:48:54.582889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932f3c331851'
down_revision: Union[str, Sequence[str], None] = '21aef34fcbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE candidatestatus ADD VALUE IF NOT EXISTS 'PENDING_REVIEW'")
        op.execute("ALTER TYPE candidatestatus ADD VALUE IF NOT EXISTS 'RESOLVED'")
    
    op.create_table('resolved_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_label', sa.String(length=255), nullable=False),
    sa.Column('synthetic_flag', sa.Boolean(), nullable=True),
    sa.Column('source_dataset', sa.String(length=255), nullable=True),
    sa.Column('provenance_mode', sa.String(length=255), nullable=True),
    sa.Column('generation_batch_id', sa.String(length=255), nullable=True),
    sa.Column('audit_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolved_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_resolved_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_resolved_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('synthetic_flag', sa.Boolean(), nullable=True),
    sa.Column('source_dataset', sa.String(length=255), nullable=True),
    sa.Column('provenance_mode', sa.String(length=255), nullable=True),
    sa.Column('generation_batch_id', sa.String(length=255), nullable=True),
    sa.Column('audit_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_resolved_entity_id'], ['resolved_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_resolved_entity_id'], ['resolved_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_entity_id', sa.UUID(), nullable=False),
    sa.Column('resolved_entity_id', sa.UUID(), nullable=True),
    sa.Column('name_similarity_score', sa.Float(), nullable=False),
    sa.Column('shared_phone_score', sa.Float(), nullable=False),
    sa.Column('shared_account_score', sa.Float(), nullable=False),
    sa.Column('spatiotemporal_overlap_score', sa.Float(), nullable=False),
    sa.Column('minilm_similarity_score', sa.Float(), nullable=True),
    sa.Column('shared_phone_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shared_account_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spatiotemporal_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_weighted_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='matchdecision'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('audit_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['candidate_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_entity_id'], ['resolved_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_entity_id', 'resolved_entity_id', name='uq_candidate_match')
    )
    op.add_column('candidate_entities', sa.Column('resolved_entity_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_entities', 'resolved_entities', ['resolved_entity_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidate_relationships', sa.Column('resolved_relationship_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_relationships', 'resolved_relationships', ['resolved_relationship_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_relationships', type_='foreignkey')
    op.drop_column('candidate_relationships', 'resolved_relationship_id')
    op.drop_constraint(None, 'candidate_entities', type_='foreignkey')
    op.drop_column('candidate_entities', 'resolved_entity_id')
    op.drop_table('candidate_matches')
    op.drop_table('resolved_relationships')
    op.drop_table('resolved_entities')
    # ### end Alembic commands ###
