"""Add file_fingerprint to ExtractionBatch

Revision ID: 9988bf5a33cc
Revises: 7f422f8d4e16
Create Date: 2026-09-09 17:26:01.017987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9988bf5a33cc'
down_revision: Union[str, Sequence[str], None] = '7f422f8d4e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_batches', sa.Column('file_fingerprint', sa.String(length=64), nullable=False))
    op.create_index('ix_extraction_unique_running_completed_fingerprint', 'extraction_batches', ['file_fingerprint'], unique=True, postgresql_where=sa.text("status IN ('RUNNING', 'COMPLETED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extraction_unique_running_completed_fingerprint', table_name='extraction_batches', postgresql_where=sa.text("status IN ('RUNNING', 'COMPLETED')"))
    op.drop_column('extraction_batches', 'file_fingerprint')
    # ### end Alembic commands ###
